# Generated by Django 4.1.7 on 2023-03-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activites/')),
            ],
        ),
    ]
