# Generated by Django 4.1.7 on 2023-03-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='participants',
            field=models.ManyToManyField(related_name='activites', to='utilisateurs.profil'),
        ),
    ]
